### ISSUE TITLE
Question: Does it fallback to /bin/cp when a flag is not supported? In other words, can I alias cp to xcp?

### ISSUE THREAD

**Issue by KSXGitHub** [tarka/xcp#22]
(I would have put this question on the Discussion tab if it was enabled)

**Comment by tarka** [comment]
Hi @KSXGitHub,

No, it doesn't fall-back. I never really intended `xcp` to be a 1-for-1 replacement for `cp`, but as a sandbox for experimenting with UI and performance improvements.

It's also worth noting that there _might_ be some problematic corner cases that `xcp` doesn't yet handle due to corresponding issues in the kernel with `copy_file_range()`; LWN has details: https://lwn.net/Articles/846403/ I have a outstanding task to implement testing of these, but the real world has been intruding recently.

Cheers,
Steve
