### ISSUE TITLE
Copying to a new file fails if source is FIFO pipe.

### ISSUE THREAD

**Issue by Notarin** [tarka/xcp#50]
## Issue
When copying from a FIFO socket, to a file that does not exist yet (the one you intend to create in the copy operation),
the following error is displayed:
`Error: Unknown file-type: $filename`
this does not happen if the copy destination file already exists.

## Reproduce
The scripts provided generally have the side-effect of performing file/pipe creations and deletions to `./source` and `./target`.
They also can write/overwrite. I make a decent effort to undo any changes.
The following scripts will produce the error:
```zsh
# FYI, this was created and tested with ZSH, but bash should play nice.
rm ./source ./target # clean workspace before starting
mkfifo ./source
xcp ./source ./target
# cleanup
rm ./source
```
```zsh
rm ./source ./target # clean workspace before starting
mkfifo ./source
(sleep 2; echo "contents" > ./source) &
xcp ./source ./target
# cleanup
rm ./source ./target
```

## Expected behavour
The failing script should perform the read from the FIFO socket as if it is a file, placing the contents into the target file.
This is expected for multiple reasons:
 - Reading from a FIFO socket is the same as reading from a file.
 - All* other utilities that performing reading functions treat a FIFO socket as expected.

*All with the caveat of a very *very* slight margin of error.

## Control tests
The following scripts do NOT fail, for the purpose of demonstrating expected behavior as well as narrowing the issue for debugging.
```zsh
# This does not fail due to creating "./test2" before invoking "xcp"
rm ./source ./target # clean workspace before starting
mkfifo ./source
touch target
(sleep 2; echo "contents" > ./source) &
xcp ./source ./target # This should block for 2 seconds
# cleanup
rm ./source ./target
```
```zsh
# This does not fail because it invokes "cp" rather than "xcp"
rm ./source ./target # clean workspace before starting
mkfifo ./source
# We did not create "./target" which causes an error in "xcp"
(sleep 2; echo "contents" > ./source) &
/bin/cp ./source ./target # This should block for 2 seconds
# cleanup
rm ./source ./target
```
```zsh
# This does not fail because it invokes "cat" rather than "xcp"
rm ./source # clean workspace before starting
mkfifo ./source
# We did not create "./target" which causes an error in "xcp"
(sleep 2; echo "contents" > ./source) &
/bin/cat ./source # This should block for 2 seconds
# cleanup
rm ./source
```

## Verbose output
`xcp --verbose ./source ./target` returns:
```
07:32:59 [INFO] Copying source "./source" to "./target"
07:32:59 [ERROR] Unknown filetype found; this should never happen!
07:32:59 [INFO] Worker received shutdown command.
07:32:59 [INFO] Worker received shutdown command.
```

## xcp version:
v0.9.4

## Further notes
It seems `tree_walker()` is treating the target differently if the source is a FIFO socket, which it shouldn't. 
I have not tested with other socket types.

**Comment by tarka** [comment]
Thanks for the detailed report. However v0.9.4 is almost a year old and much has changed since then. Ideally reports should be for the latest version. In this case, the "Unknown filetype found" error has already been fixed:

    $ mkfifo ./source
    $ xcp --no-progress -v ./source ./target
    00:41:33 [INFO] Copying source "./source" to "./target"
    00:41:33 [INFO] Worker[ThreadId(5)]: Special file "./source" -> "./target"
    00:41:33 [INFO] Copy complete
    $ ls -al source target
    prw-r--r-- 1 ssmith ssmith 0 Feb  7 11:41 source
    prw-r--r-- 1 ssmith ssmith 0 Feb  7 11:41 target

However the behaviour is not what you specified above; this is an inevitable result of how `xcp` (and other "advanced" file utilities) work. Basically `xcp` uses parallel random access into the file to accelerate copying, but a FIFO is by definition serial-only. So `xcp` just copies the FS node. You can also see this behaviour with `rsync`:

    $ rsync -Pav source target
    sending incremental file list
    source

    sent 65 bytes  received 19 bytes  168.00 bytes/sec
    total size is 0  speedup is 0.00
    $ ls -al source target
    prw-r--r-- 1 ssmith ssmith 0 Feb  7 11:41 source
    prw-r--r-- 1 ssmith ssmith 0 Feb  7 11:41 target

`cp` also behaves like this when copying recursively:

    $ mkdir tmp
    $ mkfifo tmp/fifo
    $ cp -rv tmp tmp2
    'tmp' -> 'tmp2'
    'tmp/fifo' -> 'tmp2/fifo'
    $ ls -al tmp2/
    total 8
    drwxr-xr-x 2 ssmith ssmith 4096 Feb  7 11:56 .
    drwxr-xr-x 4 ssmith ssmith 4096 Feb  7 11:56 ..
    prw-r--r-- 1 ssmith ssmith    0 Feb  7 11:56 fifo

Any recursive file copy utility has to behave like this, otherwise attempts to backup a directory that contained sockets would block attempting to read the socket.

As for the single file case, that's more of a quirk of `cp` that I probably won't emulate as it's not really what `xcp` is for; you can't accelerate FIFO copies, and there are better utilities for FIFO progress tracking e.g. `pv`. However I will add this to the list of "differences to cp" in #4.
